import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReactLenis from "lenis/react";
import { ThemeProvider } from "next-themes";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: {
    default: "My Personal Website - IG: @dhitznswa",
    template: "%s | My Personal Website - IG: @dhitznswa",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} antialiased bg-background text-foreground/70`}
      >
        <ThemeProvider attribute="class">
          <ReactLenis root>{children}</ReactLenis>
        </ThemeProvider>
      </body>
    </html>
  );
}
